[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_API_URL = "https://thora-api-333573409559.us-central1.run.app" }

[context.deploy-preview]
  environment = { VITE_API_URL = "https://thora-api-333573409559.us-central1.run.app" }
